name: spazzamento
description: "Spazzamento Toscana"
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.2.1
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  string_similarity: ^2.0.0
  supabase_flutter: ^2.4.0
  awesome_notifications: ^0.9.3+1
  timezone: ^0.9.2
  intl: ^0.19.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

dependency_overrides:
  intl: ^0.19.0

analyzer:
  errors:
    invalid_annotation_target: ignore

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env.app
    - assets/logo.png